# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59150fb85642ab39dbd825b60cab7dd7f15454bf621d94324803fbbe47c263908f176cba225d70bde61523d7715ce85649c1dcb17af423b064ae5bb2b921a888

test:
  secret_key_base: 2aaee932be605be73cfbfac7bd48b1219ce98ceaef5c4b26805d2a676b054f36ebc405096d820e146541e922a0e99a8855e32da2d50e3dddcf194d350e2f63bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
